language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build
- yarn coverage
- yarn coveralls
after_success:
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
- rsync -aP build/ $LOCATION
before_install:
- openssl aes-256-cbc -K $encrypted_d591a37e9441_key -iv $encrypted_d591a37e9441_iv
  -in deploy_key.enc -out deploy_key -d
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
